spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
    show-sql: false
    open-in-view: false
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: ${DB_URL}

local:
  image:
    root: src/test/resources

companionPlant:
  image:
    directory: photos/companionPlant

fcm:
  key:
    path: src/main/resources/config/google-services.json
