spring:
  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: false
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

local:
  url: ${SERVER_URL}
  image:
    root: resources

companionPlant:
  image:
    directory: photos/companionPlant

fcm:
  key:
    path: config/google-services.json
    scope: prod
